---
- name: Update Debian-based OS
  ansible.builtin.apt:
    update-cache: true
    upgrade: safe
  register: apt_update_result

- name: Remove unused packages
  ansible.builtin.apt:
    autoremove: true
    purge: true

- name: Show update result
  ansible.builtin.debug:
    var: apt_update_result