---
- name: Update Windows-based OS
  ansible.builtin.win_updates:
    category_names:
      - CriticalUpdates
      - SecurityUpdates
      - UpdatesRollups
      - DefinitionUpdates
      - DeveloperKits
      - FeaturePacks
      - ServicePacks
    state: installed
  register: update_result

- name: Display update results
  ansible.builtin.debug:
    msg: "Categories: {{ item.value.categories | join(', ') }} Installed Update: {{ item.value.title }} ({{ item.value.kb | join(', ') }})"
  loop: "{{ update_result.updates | dict2items }}"
    
- name: Reboot server is updates required a restart
  ansible.builtin.win_reboot:
    msg: "Updates installed. Rebooting the servers."
  when: update_result.reboot_required
